name: easy_price
description: "Easy price will easier your price showing things"
version: 0.0.8
homepage: https://github.com/jeetvaishnavnadol/easy_price.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
